language: python

jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: 3.6
      before_install:
        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - sudo apt-get install swig

    - name: "Python 3.7 on Linux"
      python: 3.7
      before_install:
        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - sudo apt-get install swig

    - name: "Python 3.8 on Linux"
      python: 3.8
      before_install:
        - export AUDIODEV=null
        - CMAKE_DIR="${TRAVIS_BUILD_DIR}/cmk"
        - mkdir ${CMAKE_DIR} && cd ${CMAKE_DIR}
        - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.tar.gz
        - tar -xvf cmake-3.17.3-Linux-x86_64.tar.gz > /dev/null
        - mv cmake-3.17.3-Linux-x86_64 cmake-install
        - PATH=${CMAKE_DIR}/cmake-install:${CMAKE_DIR}/cmake-install/bin:$PATH
        - cd ${TRAVIS_BUILD_DIR}
        - sudo apt-get install swig

install:
  - pip3 install wheel
  - pip3 install -r requirements.txt

script:
  - python3 setup.py bdist_wheel

